### ISSUE TITLE
Wordle wars landing page going into infinite loop due to CORS error

### ISSUE THREAD

**Issue by dajomareyes** [CTNicholas/wordle-wars#7]
Looks like the wordle-wars website gets stuck in an infinite loop probably because of a CORS error getting thrown on the page. See screen shot for an example.

<img width="1575" alt="image" src="https://github.com/CTNicholas/wordle-wars/assets/8964768/10de2895-e746-43f3-bee3-73f369ec3adb">

**Comment by CTNicholas** [comment]
Heya, this should be fixed now!

**Comment by dajomareyes** [comment]
Yessir! looks good thanks, closing this issue!
